Machine abstraction
hashbang/aosp-build pull request #5
Opened 2019-09-22 20:59 UTC by lrvick

* refactors container to install fixed versions of apt packages to be more deterministic
* Adds docker-machine backend allowing one to select "local" "digitalocean" or "virtualbox" backends with ability to easily add more in the future.
* Include cloud management tooling for future cloud backends and setup pattern to hash lock them

Known issues:
digitalocean support is mostly stubbed as an example and will be fleshed out and tested more in a follow up PR.

2019-09-23 02:09 UTC, drGrove requested changes

2019-09-23 02:09 UTC, drGrove commented on Makefile
> +CPUS := $(shell nproc)
nproc doesn't exist on Mac OS. Since this is in Docker/VirtualBox everything _should_ have worked normally. I'd recommend adding a check for Darwin to keep the API working.

2019-09-23 02:09 UTC, drGrove commented on Makefile
> +machine-install:
Drop this if you're not using it

2019-09-23 02:09 UTC, drGrove commented on scripts/environment
> +    base_dir = "%s/build/base" % cwd
Use format() and `{}`

2019-09-23 02:09 UTC, drGrove commented on scripts/environment
> +config_file='%s/config/config.yml' % cwd
use format() and `{}`

2019-09-23 02:09 UTC, drGrove commented on scripts/environment
> +        key_dir = "%s/config/keys/%s" % (cwd, device)
let's upgrade this to python3 while we're already making lots of changes

2019-09-23 09:45 UTC, lrvick commented on Makefile
> +CPUS := $(shell nproc)
Sugesstions for an alternative command on osx? we chould just "nproc | some-osx-bs"

2019-10-27 15:32 UTC, ypid reviewed
Impressive work @lrvick :+1:

I like the idea to pin the Docker images and also the apt packages. Also, I like the overall structure of build system so that https://github.com/hashbang/os or other ROMs can use one robust build system.

I left a few small comments. Additionally, I interactively reviewed this PR, fixed a few things and made it work for me. For example, I don’t want to have some big go projects in my TCB so I worked out a way that should be suitable for us all. For people who want to integrate this with Kubernets and so on. And for me who wants to have a minimal build system that I can review/understand as much as possible. Also, I still like to build all the Docker (base/child) images myself. Let me know what you think: https://github.com/hashbang/aosp-build/pull/7

2019-10-27 15:32 UTC, ypid commented on config/container/Dockerfile
> +ARG TERRAFORM_KUBERNETES_GIT_REF="56bb8e012f5f4bdd2fb906e1e6a567e3e57b46a4"
What is the reason for listing the GIT_REFs as ARG here instead of just writing it directly in the `printf` command? My guess is that you want to allow overwriting it using the `--build-arg` option? Is that actually used/needed?

2019-10-27 15:32 UTC, ypid commented on scripts/environment
> +    "MANIFEST_DIR": "%s/config/manifests" % cwd,
Seems one of those can be removed now that they are the same?

2019-11-11 07:02 UTC, drGrove commented on config/container/Dockerfile
> +ARG TERRAFORM_KUBERNETES_GIT_REF="56bb8e012f5f4bdd2fb906e1e6a567e3e57b46a4"
It's a nice abstraction that allows for testing upgrades in the future as well as something we do in other projects

2019-11-23 15:47 UTC, ypid commented
cc: @lsfxz you might also be interested in the work that Hashbang OS is doing (ref: https://github.com/lsfxz/AOSP-Build-Environment-Docker).

I also informed @Trumeet in https://github.com/Trumeet/AOSP-Build-Environment-Docker/issues/3.

2019-11-27 15:26 UTC, lrvick commented
@drGrove Considering the Android 9 setup is no longer updated and has known CVEs I think we should just do a hard cut to this into master at this point given that it has been tested by myself and ypid.

We keep merging PRs into this branch and it might as well be master at this point.

Thoughts?

2019-11-27 15:37 UTC, lrvick commented
@drGrove addressed all your comments in last commit

2019-11-27 15:41 UTC, lrvick commented on config/container/Dockerfile
> +ARG TERRAFORM_KUBERNETES_GIT_REF="56bb8e012f5f4bdd2fb906e1e6a567e3e57b46a4"
Yeah it allows you to override these in a separate file via --build-arg.

The intention is to have "make config" be able to bump these automatically in a future revision

2019-12-01 09:28 UTC, drGrove approved these changes

2019-12-01 09:28 UTC, merged